<?php

namespace App\Repository;

use App\Document\CodeInvitation;
use Doctrine\ODM\MongoDB\Repository\DocumentRepository;

/**
 * CodeInvitationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeInvitationRepository extends DocumentRepository
{
    public function findAllOrderedByPosition()
    {
        return $this->createQueryBuilder()
          ->sort('id', 'ASC')
          ->getQuery();
          //->execute();
    }

    public function codeInvitationIsValid($userCodeInvitation)
    {
        /*$test = $this->getRepository(CodeInvitation::class)->find($userCodeInvitation);

        if($test == null){
            return false;
        }else{
            return true;
        }*/


        $test = $this->createQueryBuilder('obj') 
        ->where("obj.code = :$userCodeInvitation")
        ->select('obj.code');

        if($test == $userCodeInvitation){
            return true;
        }else{
            return false;
        }
        
    }
}
