<?php

namespace App\Repository;

use App\Document\CodeInvitation;
use Doctrine\ODM\MongoDB\Repository\DocumentRepository;
use \Datetime;

/**
 * CodeInvitationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeInvitationRepository extends DocumentRepository
{
    public function findAllOrderedByPosition()
    {
        return $this->createQueryBuilder()
          ->sort('id', 'ASC')
          ->getQuery();
          //->execute();
    }

    public function codeInvitationIsValid($userCodeInvitation)
    {
        $key = $this->findOneBY(['code' => $userCodeInvitation, 'active' => true]);
        
        if($key==null){
            return false;
        }else{
            $today = new DateTime('NOW');
            if($today > $key->getDate()) {
                $this->findOneBY(['code' => $userCodeInvitation])->setActive(false);
                return false;
            } else {
                $this->findOneBY(['code' => $userCodeInvitation])->setUsable($key->getUsable()-1);
                if($key->getUsable()<=0){
                    $this->findOneBY(['code' => $userCodeInvitation])->setActive(false);
                }
                return true; 
            }
        }
    }
}
